version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: z-frontend
    image: frontend:latest
    ports:
      - "3000:3000"
    networks:
      - Z-Learning-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: z-backend
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - Z-Learning-network

  mongodb:
    image: mongo
    container_name: z-Learning
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - Z-Learning-network

  mongo-express:
    image: mongo-express
    container_name: z-Learning-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - Z-Learning-network

volumes:
  mongodb-data:

networks:
  Z-Learning-network:
